# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5e55f4f962c997bb1efe7a74fcab0a846eadb2df55243b4a0361c0d2ad8fa2326c8787a4fd3543c003a0540aff8ecec8936d3fb52195649de28e7f8aced5708

test:
  secret_key_base: 85537bf500e36944f808bfdd947de5fcb2a9d6c0a557ab7d3486fc8f22569fc2961fdb4bb0a1fade54117454a7cf35b5663fb202daa8dc3d208faf7d78db1e69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
